/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts/new'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts/$workoutId'
import { Route as ExercisesExerciseIdHistoryRouteImport } from './routes/exercises/$exerciseId/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdHistoryRoute =
  ExercisesExerciseIdHistoryRouteImport.update({
    id: '/exercises/$exerciseId/history',
    path: '/exercises/$exerciseId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/exercises/$exerciseId/history': typeof ExercisesExerciseIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises': typeof ExercisesIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/exercises/$exerciseId/history': typeof ExercisesExerciseIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/exercises/$exerciseId/history': typeof ExercisesExerciseIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/exercises/'
    | '/workouts/'
    | '/exercises/$exerciseId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/exercises'
    | '/workouts'
    | '/exercises/$exerciseId/history'
  id:
    | '__root__'
    | '/'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/exercises/'
    | '/workouts/'
    | '/exercises/$exerciseId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  ExercisesExerciseIdHistoryRoute: typeof ExercisesExerciseIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId/history': {
      id: '/exercises/$exerciseId/history'
      path: '/exercises/$exerciseId/history'
      fullPath: '/exercises/$exerciseId/history'
      preLoaderRoute: typeof ExercisesExerciseIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  ExercisesExerciseIdHistoryRoute: ExercisesExerciseIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
